services:
  cdn:
    build: .
    ports:
      - "8080:8080"
    environment:
      BASE_FQDN: example.com
    volumes:
      - ./example/public:/public:ro
    develop:
      watch:
        - action: rebuild
          path: internal
        - action: rebuild
          path: cmd
        - action: rebuild
          path: go.mod
