services:
  cdn:
    build: .
    ports:
      - "8080:8080"
    environment:
      BASE_FQDN: karakosystems.com
    develop:
      watch:
        - action: rebuild
          path: assets
        - action: rebuild
          path: internal
        - action: rebuild
          path: cmd
        - action: rebuild
          path: embed.go
        - action: rebuild
          path: go.mod
